In [39]:
import numpy as np
from scipy.sparse.linalg import svds


In [40]:
# R = np.array([
#     [5, 3, 0, 1],
#     [4, 0, 0, 1],
#     [1, 1, 0, 5],
#     [1, 0, 0, 4],
#     [0, 1, 5, 4],
# ])
R = np.array([
    [1, 1, 0, 1],
    [1, 0, 1, 1],
    [1, 1, 0, 1],
    [1, 0, 0, 0],
    [0, 1, 0, 1],
])
# Tính trung bình đánh giá của mỗi người dùng
user_ratings_mean = np.mean(R, axis=1)
R_demeaned = R - user_ratings_mean.reshape(-1, 1)


In [41]:
user_ratings_mean.reshape(-1, 1)

array([[0.75],
       [0.75],
       [0.75],
       [0.25],
       [0.5 ]])

In [42]:
U, sigma, Vt = svds(R_demeaned, k=1)
sigma = np.diag(sigma)


In [43]:
R_predicted = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
print("Ma trận đánh giá dự đoán:")
print(R_predicted)


Ma trận đánh giá dự đoán:
[[ 0.64280339  1.17475462  0.19725943  0.98518256]
 [ 0.83237545  0.42359645  1.17475462  0.56927348]
 [ 0.64280339  1.17475462  0.19725943  0.98518256]
 [ 0.27078934  0.16762455  0.35719661  0.2043895 ]
 [ 0.37201405  1.00713007 -0.15993717  0.78079305]]


In [44]:
def recommend_games(R_predicted, user_id, original_ratings, num_recommendations=5):
    user_row_number = user_id - 1  # Chỉ số hàng của người dùng trong ma trận
    sorted_user_predictions = R_predicted[user_row_number].argsort()[::-1]  # Sắp xếp theo thứ tự giảm dần

    print(f"Top {num_recommendations} game được gợi ý cho người dùng {user_id}:")
    for i in sorted_user_predictions[:num_recommendations]:
        print(f"Game {i + 1} với đánh giá dự đoán {R_predicted[user_row_number, i]:.2f}")

# Ví dụ: Gợi ý game cho người dùng 1
recommend_games(R_predicted, user_id=5, original_ratings=R)


Top 5 game được gợi ý cho người dùng 5:
Game 2 với đánh giá dự đoán 1.01
Game 4 với đánh giá dự đoán 0.78
Game 1 với đánh giá dự đoán 0.37
Game 3 với đánh giá dự đoán -0.16


In [45]:
a = R_predicted[4].argsort()[::-1]